
# PROMPT
export IMPROMPTU_PROMPT_ADD_NEWLINE="true"
export IMPROMPTU_PROMPT_SEPARATE_LINE="true"
export IMPROMPTU_PROMPT_FIRST_PREFIX_SHOW="false"
export IMPROMPTU_PROMPT_PREFIXES_SHOW="true"
export IMPROMPTU_PROMPT_SUFFIXES_SHOW="true"
export IMPROMPTU_PROMPT_DEFAULT_PREFIX="via "
export IMPROMPTU_PROMPT_DEFAULT_SUFFIX=" "
